// Central SEO config so metadata, robots, sitemap and JSON-LD stay in sync.
export const SITE = {
  name: "Carva",
  url: "https://carvarent.com",
  // Brand variations people search for — surfaced in <title>, JSON-LD
  // alternateName and keywords so the brand resolves to this site.
  alternateNames: [
    "Carva Rent",
    "Carva Rent Car",
    "Carva Car Rental",
    "Carvaone",
    "CarvaOne",
    "کارڤا",
    "كارفا",
  ],
  description:
    "Carva (Carva Rent) is a car rental marketplace in Iraq and Kurdistan. Browse rental cars from trusted offices in Erbil, Sulaymaniyah and Duhok, compare photos, specs and prices, then reserve online or contact the office on WhatsApp.",
  tagline: "Carva — Rent a car in Iraq & Kurdistan",
  logo: "/assets/images/carva.png",
} as const;

export const SEO_KEYWORDS = [
  "Carva",
  "Carva Rent",
  "Carva rent car",
  "Carva car rental",
  "Carvaone",
  "CarvaOne",
  "car rental",
  "rent a car",
  "car rental Iraq",
  "car rental Kurdistan",
  "rent a car Erbil",
  "rent a car Sulaymaniyah",
  "rent a car Duhok",
  "rent a car Baghdad",
  "کارڤا",
  "کرێی سەیارە",
  "ئۆتۆمبێل بە کرێ",
  "سەیارە بە کرێ",
  "كارفا",
  "تأجير سيارات",
  "تأجير سيارات اربيل",
  "تأجير سيارات السليمانية",
  "ايجار سيارات العراق",
  "airport car rental Erbil",
  "airport car rental Sulaymaniyah",
  "Erbil airport pickup",
  "daily car rental Iraq",
  "weekly car rental Iraq",
  "monthly car rental Iraq",
  "long term car rental Kurdistan",
  "SUV rental Iraq",
  "luxury car rental Iraq",
  "economy car rental Kurdistan",
  "cheap car rental Kurdistan",
  "best car rental company Iraq",
  "car rental companies Erbil",
  "rent a car near me",
  "book rental car online",
  "کرێی ئۆتۆمبێل",
  "بەکرێدانی سەیارە",
  "کرێی سەیارە لە هەولێر",
  "کرێی سەیارە لە سلێمانی",
  "کرێی سەیارە لە دهۆک",
  "گواستنەوەی فڕۆکەخانە",
  "تأجير سيارات مع سائق",
  "تأجير سيارات المطار",
  "حجز سيارة أونلاين",
];
